#!/usr/bin/env python3
"""
Project memory shared across AI dev tools — Claude Code, Cursor, Codex CLI,
Roo Code, Cline, Aider, Windsurf — from one canonical source.

Source of truth:  .claude-context/MEMORY.md  (+ memory/*.md)
                  ↓ generated on `push`
Local adapters:   CLAUDE.md, .cursor/rules/memory.mdc, .roo/rules/memory.md,
                  .clinerules, AGENTS.md, .windsurfrules

The source is committed to git; the adapters are typically gitignored (they're
per-machine projections). Run on every clone to regenerate them locally.

Usage:
    python scripts/sync-tools.py detect          # show which tools we'll write for
    python scripts/sync-tools.py push             # generate adapter files
    python scripts/sync-tools.py push --dry-run   # show what would change
    python scripts/sync-tools.py push --only cursor,claude

No external dependencies — stdlib only.
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path.cwd()
SOURCE_DIR = ROOT / ".claude-context"
SOURCE_INDEX = SOURCE_DIR / "MEMORY.md"
SOURCE_MEMORY = SOURCE_DIR / "memory"

# Each adapter: (id, label, output path relative to ROOT, "always" or "if-detected")
#
#   always       → we'll write it for every project (it's harmless to have)
#   if-detected  → only write if the tool's config dir/file already exists
#                  (avoids polluting projects that don't use the tool)
ADAPTERS = [
    {"id": "claude",  "label": "Claude Code",     "path": "CLAUDE.md",                 "mode": "always",      "detect": []},
    {"id": "cursor",  "label": "Cursor",          "path": ".cursor/rules/memory.mdc",  "mode": "if-detected", "detect": [".cursor", ".cursorrules"]},
    {"id": "roo",     "label": "Roo Code",        "path": ".roo/rules/memory.md",      "mode": "if-detected", "detect": [".roo", ".rooignore"]},
    {"id": "cline",   "label": "Cline",           "path": ".clinerules/memory.md",     "mode": "if-detected", "detect": [".clinerules"]},
    {"id": "codex",   "label": "Codex CLI",       "path": "AGENTS.md",                 "mode": "if-detected", "detect": [".codex", "AGENTS.md"]},
    {"id": "aider",   "label": "Aider",           "path": "CONVENTIONS.md",            "mode": "if-detected", "detect": [".aider", "CONVENTIONS.md", ".aider.conf.yml"]},
    {"id": "windsurf","label": "Windsurf",        "path": ".windsurfrules",            "mode": "if-detected", "detect": [".windsurfrules", ".windsurf"]},
]

AUTO_GEN_HEADER = """<!--
  AUTO-GENERATED by `python scripts/sync-tools.py push`.
  Source of truth: .claude-context/MEMORY.md (+ memory/*.md)
  Edit the source, then re-run sync-tools to regenerate this file.
  Manual edits here will be overwritten.
-->
"""

def detected(adapter: dict) -> bool:
    if adapter["mode"] == "always":
        return True
    return any((ROOT / marker).exists() for marker in adapter["detect"])


def assemble_memory() -> str:
    """Build the canonical memory block from MEMORY.md + memory/*.md."""
    if not SOURCE_INDEX.exists():
        print(f"  ✗ No {SOURCE_INDEX} — run /sync export first.", file=sys.stderr)
        sys.exit(1)

    parts = [SOURCE_INDEX.read_text().strip(), ""]

    if SOURCE_MEMORY.exists():
        memory_files = sorted(SOURCE_MEMORY.glob("*.md"))
        if memory_files:
            parts.append("---\n")
            parts.append("## Memory entries\n")
            for f in memory_files:
                parts.append(f"### {f.name}\n")
                parts.append(f.read_text().strip())
                parts.append("")
    return "\n".join(parts).strip() + "\n"


def render_for(adapter: dict, body: str) -> str:
    """Wrap the canonical body with whatever frontmatter the target tool needs."""
    if adapter["id"] == "cursor":
        # Cursor .mdc files take YAML frontmatter
        return (
            "---\n"
            "description: Project memory (auto-synced from .claude-context/MEMORY.md)\n"
            "globs: [\"**/*\"]\n"
            "alwaysApply: true\n"
            "---\n\n"
            + AUTO_GEN_HEADER + "\n"
            + body
        )
    return AUTO_GEN_HEADER + "\n" + body


def cmd_detect():
    print(f"Project root: {ROOT}\n")
    print(f"Source: {SOURCE_INDEX} {'✓' if SOURCE_INDEX.exists() else '✗ (run /sync export first)'}")
    if SOURCE_MEMORY.exists():
        n = len(list(SOURCE_MEMORY.glob('*.md')))
        print(f"        {SOURCE_MEMORY} ({n} memory file(s))")
    print()
    print("Adapter targets:")
    for a in ADAPTERS:
        on = detected(a)
        marker = "✓" if on else "○"
        why = "always" if a["mode"] == "always" else (
            f"detected ({', '.join(m for m in a['detect'] if (ROOT / m).exists())})"
            if on else f"not detected (looking for: {', '.join(a['detect'])})"
        )
        print(f"  [{marker}] {a['label']:<14} → {a['path']:<32}  {why}")


def cmd_push(only: set[str] | None, dry_run: bool):
    body = assemble_memory()
    written = []
    skipped = []
    for a in ADAPTERS:
        if only and a["id"] not in only:
            skipped.append((a, "filtered by --only"))
            continue
        if not detected(a):
            skipped.append((a, f"not detected (no {a['detect']})"))
            continue
        out = ROOT / a["path"]
        content = render_for(a, body)
        if dry_run:
            existed = "rewriting" if out.exists() else "creating"
            print(f"  [dry-run] {a['label']:<14} {existed} {out.relative_to(ROOT)} ({len(content):,} bytes)")
        else:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(content)
            print(f"  ✓ {a['label']:<14} → {out.relative_to(ROOT)} ({len(content):,} bytes)")
        written.append(a)

    print()
    if skipped:
        print("Skipped:")
        for a, why in skipped:
            print(f"  - {a['label']:<14} ({why})")
    if not dry_run and written:
        manifest = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "source": ".claude-context/MEMORY.md",
            "targets": [a["id"] for a in written],
        }
        (ROOT / ".claude-context" / "sync-tools-manifest.json").write_text(
            json.dumps(manifest, indent=2) + "\n"
        )
        print(f"\nWrote {len(written)} adapter file(s). Manifest: .claude-context/sync-tools-manifest.json")
        print("Note: most adapter files are typically gitignored (per-machine projections).")


def main():
    p = argparse.ArgumentParser(description="Share project memory across AI dev tools")
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("detect", help="show which adapter targets would be written")
    pp = sub.add_parser("push", help="generate adapter files from .claude-context/MEMORY.md")
    pp.add_argument("--dry-run", action="store_true", help="show changes without writing")
    pp.add_argument("--only", help="comma-separated adapter ids (e.g. cursor,claude)")
    args = p.parse_args()

    if args.cmd == "detect":
        cmd_detect()
    elif args.cmd == "push":
        only = set(s.strip() for s in args.only.split(",")) if args.only else None
        cmd_push(only, args.dry_run)


if __name__ == "__main__":
    main()
